# Generated by Django 2.2.4 on 2021-05-20 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dantai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='団体マスタ')),
            ],
            options={
                'verbose_name': '所属団体マスタ',
                'verbose_name_plural': '所属団体マスタ',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='顧客名')),
                ('address', models.CharField(blank=True, max_length=40, null=True, verbose_name='住所')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='メール')),
                ('todofuken', models.IntegerField(blank=True, choices=[(1, '北海道'), (2, '青森県'), (3, '岩手県'), (4, '宮城県'), (5, '秋田県'), (6, '山形県'), (7, '福島県'), (8, '茨城県'), (9, '栃木県'), (10, '群馬県'), (11, '埼玉県'), (12, '千葉県'), (13, '東京都'), (14, '神奈川県'), (15, '新潟県'), (16, '富山県'), (17, '石川県'), (18, '福井県'), (19, '山梨県'), (20, '長野県'), (21, '岐阜県'), (22, '静岡県'), (23, '愛知県'), (24, '三重県'), (25, '滋賀県'), (26, '京都府'), (27, '大阪府'), (28, '兵庫県'), (29, '奈良県'), (30, '和歌山県'), (31, '鳥取県'), (32, '島根県'), (33, '岡山県'), (34, '広島県'), (35, '山口県'), (36, '徳島県'), (37, '香川県'), (38, '愛媛県'), (39, '高知県'), (40, '福岡県'), (41, '佐賀県'), (42, '長崎県'), (43, '熊本県'), (44, '大分県'), (45, '宮崎県'), (46, '鹿児島県'), (47, '沖縄県 ')], null=True, verbose_name='都道府県')),
                ('leaseDate', models.DateField(blank=True, null=True, verbose_name='リース期限')),
                ('onlineSupport', models.BooleanField(verbose_name='オンラインサポート')),
                ('hpUrl', models.URLField(blank=True, max_length=100, null=True, verbose_name='HPのURL')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='作成時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='更新時間')),
                ('Dantai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Dantai', to='app.Dantai', verbose_name='所属団体（マスタ連動）')),
            ],
            options={
                'verbose_name': '顧客マスタ',
                'verbose_name_plural': '顧客マスタ',
            },
        ),
    ]
