# Generated by Django 2.2.4 on 2021-05-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210520_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='name_furigana',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='フリガナ'),
        ),
    ]
