# Generated by Django 2.2.4 on 2021-05-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210521_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='todofuken',
            new_name='address1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='address',
        ),
        migrations.AddField(
            model_name='item',
            name='address2',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='市町村番地'),
        ),
        migrations.AddField(
            model_name='item',
            name='address3',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='建物名'),
        ),
        migrations.AddField(
            model_name='item',
            name='postcode',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='郵便番号'),
        ),
    ]
