# Generated by Django 2.2.4 on 2021-05-24 07:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210524_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name_furigana',
            field=models.CharField(blank=True, default='', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='全角フリガナ20文字以内で入力して下さい', regex='^[ァ-ヶ]+$')], verbose_name='フリガナ'),
        ),
        migrations.AlterField(
            model_name='item',
            name='postcode',
            field=models.CharField(blank=True, default='', max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='半角数字7文字（ハイフン「-」無し）で入力して下さい', regex='^[0-9]+$'), django.core.validators.MinLengthValidator(7)], verbose_name='郵便番号'),
        ),
    ]
